# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Voi Swarm
site_description: Create and run a Voi Network Participation Node
site_url: https://voinetwork.github.io/voi-swarm/
repo_url: https://github.com/VoiNetwork/voi-swarm
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  logo: assets/Voi_Logo_White_on_Purple_Background.png
  favicon: assets/favicon.ico
  palette:
    primary: custom
  features:
    - navigation.instant
    - navigation.instant.progress
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Voi_Net
    - icon: fontawesome/brands/github
      link: https://github.com/VoiNetwork/voi-swarm
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/vnFbrJrHeW
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  analytics:
    provider: google
    property: G-FXJF968XD5
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            joining <a href="https://discord.com/invite/vnFbrJrHeW">our Discord</a>.

copyright:
  <a href="#__consent">Change cookie settings</a>

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - pymdownx.snippets:
      base_path: "docs"
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - search
  - social:
      cards_layout: default/variant
      cards_layout_options:
        background_color: "#702AE2"
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
  - git-authors
  - privacy

extra_css:
  - stylesheets/extra.css

nav:
  - Voi Chain:
      - Overview: index.md
      - Using Voi:
          - Create A Wallet: ecosystem/wallets.md
          - Build On Voi: developers/start-here.md
      - Airdrops:
          - Overview: airdrops/overview.md
          - Incentivized Testnet: airdrops/incentivized-testnet.md
          - Socials: airdrops/socials.md
          - Project Engagement: airdrops/engagement.md
          - Token Sale: airdrops/token-sale.md
  - Ecosystem:
      - Wallets: ecosystem/wallets.md
      - Community: ecosystem/community.md
      - Governance:
          - Governance: ecosystem/governance.md
          - Submitting Proposals: ecosystem/submitting-proposals.md
      - Projects: ecosystem/projects.md
      - Tokenomics: ecosystem/tokenomics.md
      - Roadmap: ecosystem/roadmap.md
  - Developers:
      - Start Here: developers/start-here.md
      - API: developers/api.md
      - SDK: developers/sdk.md
      - Smart Contracts: developers/smart-contracts.md
      - Networks: developers/networks.md
  - Node Runners:
      - Voi Swarm:
          - Introduction: introduction.md
          - Getting Started:
              - Introduction: getting-started/introduction.md
          - Installation:
              - System requirements: installation/system-requirements.md
              - Prerequisites: installation/prerequisites.md
              - Installation: installation/installation.md
              - Installation (advanced): installation/installation-advanced.md
              - Uninstall: installation/uninstall.md
          - Updating:
              - Updating Voi Swarm: updating/swarm-update.md
              - Telemetry name: updating/telemetry.md
          - Operating:
              - Running your node: operating/running-your-node.md
              - Participation keys: operating/participation-keys.md
              - Setup notifications: operating/setup-notifications.md
          - Notification Guides:
              - Amazon SES: notification-guides/amazon-ses.md
              - Email: notification-guides/email.md
              - Pushbullet: notification-guides/pushbullet.md
          - Provider Guidance: provider-guidance.md
          - Migrating to Voi Swarm: migrating.md
          - CLI Tools: cli-tools.md
          - Troubleshooting: troubleshooting.md